apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - policy-disallow-latest.yaml
  - policy-require-requests-limits.yaml
  - policy-restrict-root.yaml
  - policy-readonly-rootfs.yaml
  - policy-disallow-hostpath.yaml
  - policy-block-host-namespaces.yaml
  - policy-require-labels.yaml
