apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bootstrap-dev-secrets.yaml
  - secretstore-local-kubernetes.yaml
  - secretstore-aws-asm.yaml
  - externalsecret-srotas-main.yaml
  - externalsecret-redis.yaml
