apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: echo-tls
  namespace: apps
spec:
  secretName: echo-tls
  issuerRef:
    kind: ClusterIssuer
    name: mkcert-cluster-issuer
  dnsNames:
    - echo.127.0.0.1.nip.io
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: srotas-echo
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: mkcert-cluster-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - secretName: echo-tls
      hosts:
        - echo.127.0.0.1.nip.io
  rules:
    - host: echo.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: srotas-echo
                port:
                  number: 8080
