apiVersion: v1
kind: ConfigMap
metadata:
  name: srotas-ms-mcp-config
  namespace: apps
  labels:
    app.kubernetes.io/part-of: srotas
data:
  ENVIRONMENT: "development"
  RUST_LOG: "actix_web=debug,info"