apiVersion: v1
kind: ConfigMap
metadata:
  name: srotas-main-config
  namespace: apps
  labels:
    app.kubernetes.io/part-of: srotas
data:
  ENVIRONMENT: "development"
  RUST_LOG: "actix_web=debug,info"
  MCP_BASE_URL: "http://srotas-ms-mcp.apps.svc.cluster.local:8081"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000"