apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: srotas-main
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: mkcert-cluster-issuer
spec:
  ingressClassName: traefik
  tls:
  - hosts: [ "api.srotas.127.0.0.1.nip.io" ]
    secretName: srotas-local-tls
  rules:
  - host: api.srotas.127.0.0.1.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: srotas-main
            port:
              number: 8080
